export const WORDS_LIST_REQUEST = "WORDS_LIST_REQUEST";
export const WORDS_LIST_SUCCESS = "WORDS_LIST_SUCCESS";
export const WORDS_LIST_FAIL = "WORDS_LIST_FAIL";

export const WORDS_CREATE_REQUEST = "WORDS_CREATE_REQUEST";
export const WORDS_CREATE_SUCCESS = "WORDS_CREATE_SUCCESS";
export const WORDS_CREATE_FAIL = "WORDS_CREATE_FAIL";

export const WORDS_UPDATE_REQUEST = "WORDS_UPDATE_REQUEST";
export const WORDS_UPDATE_SUCCESS = "WORDS_UPDATE_SUCCESS";
export const WORDS_UPDATE_FAIL = "WORDS_UPDATE_FAIL";

export const WORDS_DELETE_REQUEST = "WORDS_DELETE_REQUEST";
export const WORDS_DELETE_SUCCESS = "WORDS_DELETE_SUCCESS";
export const WORDS_DELETE_FAIL = "WORDS_DELETE_FAIL";